FILMES = {
    "acao": [
        {"titulo": "Mad Max: Estrada da Fúria", "ano": 2015, "descricao": "Uma mulher rebelde e um fugitivo cruzam um mundo pós-apocalíptico em busca de liberdade."},
        {"titulo": "John Wick", "ano": 2014, "descricao": "Um ex-assassino volta à ativa para se vingar da morte de seu cachorro."},
        {"titulo": "Top Gun: Maverick", "ano": 2022, "descricao": "Maverick volta a treinar jovens pilotos de elite para uma missão impossível."},
        {"titulo": "Missão Impossível: Acerto de Contas", "ano": 2023, "descricao": "Ethan Hunt enfrenta sua missão mais perigosa para salvar o mundo."},
        {"titulo": "Os Vingadores", "ano": 2012, "descricao": "Heróis da Marvel se unem para salvar a Terra de Loki e seu exército alienígena."},
    ],
    "comedia": [
        {"titulo": "Se Beber, Não Case!", "ano": 2009, "descricao": "Quatro amigos acoram em Las Vegas e precisam descobrir o que aconteceu na noite anterior."},
        {"titulo": "Todo Mundo em Pânico", "ano": 2000, "descricao": "Uma paródia hilária dos filmes de terror dos anos 90."},
        {"titulo": "Superbad", "ano": 2007, "descricao": "Dois amigos tentam aproveitar ao máximo o último ano do ensino médio."},
        {"titulo": "A Grande Viagem", "ano": 2006, "descricao": "Um grupo de idosos foge do asilo para ver um jogo de futebol americano."},
        {"titulo": "Debi e Loide: Dois Idiotas em Apuros", "ano": 1994, "descricao": "Um motorista e seu amigo embarcam em uma divertida viagem por Aspen para devolver uma maleta ao proprietário."},
    ],
    "drama": [
        {"titulo": "O Poderoso Chefão", "ano": 1972, "descricao": "A saga da família Corleone, uma das mais poderosas da máfia americana."},
        {"titulo": "Clube da Luta", "ano": 1999, "descricao": "Um homem insatisfeito com a vida cria um clube clandestino de lutas."},
        {"titulo": "Forrest Gump", "ano": 1994, "descricao": "A história de um homem simples que, sem querer, participa de eventos históricos dos EUA."},
        {"titulo": "À Espera de um Milagre", "ano": 1999, "descricao": "Um guarda de prisão convive com um presidiário que possui poderes misteriosos."},
        {"titulo": "Interestelar", "ano": 2014, "descricao": "Astronautas viajam por um buraco de minhoca em busca de um novo lar para a humanidade."},
    ],
    "terror": [
        {"titulo": "O Iluminado", "ano": 1980, "descricao": "Um escritor leva a família para um hotel isolado e começa a enlouquecer."},
        {"titulo": "Hereditário", "ano": 2018, "descricao": "Após a morte da matriarca, uma família começa a revelar segredos sombrios."},
        {"titulo": "It: A Coisa", "ano": 2017, "descricao": "Um grupo de crianças enfrenta uma entidade maligna que se disfarça de palhaço."},
        {"titulo": "A Bruxa", "ano": 2015, "descricao": "Uma família puritana é aterrorizada por forças sobrenaturais na Nova Inglaterra do século XVII."},
        {"titulo": "Get Out", "ano": 2017, "descricao": "Um homem negro visita a família da namorada e descobre algo perturbador."},
    ],
    "romance": [
        {"titulo": "Titanic", "ano": 1997, "descricao": "Um amor improvável nasce entre duas pessoas de classes sociais opostas no navio mais famoso da história."},
        {"titulo": "Diário de uma Paixão", "ano": 2004, "descricao": "Um casal de jovens vive um romance intenso nos anos 40 nos EUA."},
        {"titulo": "La La Land", "ano": 2016, "descricao": "Um pianista e uma aspirante a atriz se apaixonam em Los Angeles e perseguem seus sonhos."},
        {"titulo": "Simplesmente Amor", "ano": 2003, "descricao": "Várias histórias de amor se entrelaçam em Londres durante o Natal."},
        {"titulo": "Teoria de Tudo", "ano": 2014, "descricao": "A história de amor entre Stephen Hawking e sua primeira esposa Jane."},
    ],
    "ficcao_cientifica": [
        {"titulo": "Matrix", "ano": 1999, "descricao": "Um hacker descobre que o mundo em que vive é uma simulação controlada por máquinas."},
        {"titulo": "Duna", "ano": 2021, "descricao": "Um jovem nobre assume o destino de um planeta desértico com o recurso mais valioso do universo."},
        {"titulo": "Blade Runner 2049", "ano": 2017, "descricao": "Um caçador de replicantes descobre um segredo que pode mudar o futuro da humanidade."},
        {"titulo": "Arrival", "ano": 2016, "descricao": "Uma linguista tenta se comunicar com alienígenas que chegam à Terra."},
        {"titulo": "Ex Machina", "ano": 2014, "descricao": "Um programador é escolhido para avaliar a inteligência de uma robô com aparência humana."},
    ],
    "animacao": [
        {"titulo": "Homem-Aranha no Aranhaverso", "ano": 2018, "descricao": "Miles Morales se torna o Homem-Aranha e conhece versões alternativas do herói."},
        {"titulo": "Viva: A Vida é uma Festa", "ano": 2017, "descricao": "Um garoto mexicano visita o mundo dos mortos em busca de seu bisavô músico."},
        {"titulo": "Soul", "ano": 2020, "descricao": "Um músico de jazz tem sua alma separada do corpo e precisa voltar à vida."},
        {"titulo": "O Rei Leão", "ano": 1994, "descricao": "Um leão é exilado após ser acusado da morte do pai e precisa reconquistar seu reino."},
        {"titulo": "Spirited Away", "ano": 2001, "descricao": "Uma garota entra em um mundo espiritual e precisa trabalhar para salvar seus pais."},
    ],
    "suspense": [
        {"titulo": "Parasita", "ano": 2019, "descricao": "Uma família pobre se infiltra na vida de uma família rica com consequências imprevisíveis."},
        {"titulo": "Whiplash", "ano": 2014, "descricao": "Um jovem baterista é submetido a um treinamento extremo por um professor obsessivo."},
        {"titulo": "Zodíaco", "ano": 2007, "descricao": "Um cartunista de jornal fica obcecado em descobrir a identidade do assassino Zodíaco."},
        {"titulo": "Oldboy", "ano": 2003, "descricao": "Um homem é libertado após 15 anos preso sem saber o motivo e busca vingança."},
        {"titulo": "Primal Fear", "ano": 1996, "descricao": "Um advogado defende um jovem acusado de assassinato e descobre camadas de manipulação."},
    ],
    "aventura": [
        {"titulo": "Indiana Jones e os Caçadores da Arca Perdida", "ano": 1981, "descricao": "Um arqueólogo aventureiro corre contra o tempo para encontrar a Arca da Aliança antes dos nazistas."},
        {"titulo": "Jurassic Park", "ano": 1993, "descricao": "Um parque temático com dinossauros clonados entra em colapso quando os animais escapam."},
        {"titulo": "Piratas do Caribe: A Maldição do Pérola Negra", "ano": 2003, "descricao": "Um pirata excêntrico e um ferreiro se unem para resgatar uma jovem de uma maldição."},
        {"titulo": "O Hobbit: Uma Jornada Inesperada", "ano": 2012, "descricao": "Um hobbit relutante parte em uma jornada épica com um grupo de anões para reconquistar um tesouro."},
        {"titulo": "A Múmia", "ano": 1999, "descricao": "Um arqueólogo acidentalmente desperta uma múmia milenar no Egito."},
    ],
    "cinema_tv": [
        {"titulo": "Black Mirror: Bandersnatch", "ano": 2018, "descricao": "Um jovem programador começa a questionar a realidade enquanto adapta um livro em um videogame."},
        {"titulo": "El Camino: Um Filme de Breaking Bad", "ano": 2019, "descricao": "Jesse Pinkman foge das consequências de seus crimes e tenta reconstruir a vida."},
        {"titulo": "Deadwind", "ano": 2018, "descricao": "Uma detetive investiga um assassinato misterioso enquanto lida com sua própria tragédia pessoal."},
        {"titulo": "Sherlock: O Abominável Noivo", "ano": 2016, "descricao": "Sherlock Holmes investiga um caso sobrenatural na Era Vitoriana."},
        {"titulo": "Twin Peaks: O Retorno", "ano": 2017, "descricao": "O agente Dale Cooper retorna a Twin Peaks após décadas para desvendar novos mistérios."},
    ],
    "crime": [
        {"titulo": "Pulp Fiction", "ano": 1994, "descricao": "Histórias de gangsters, assassinos e ladrões se entrelaçam em Los Angeles de forma não linear."},
        {"titulo": "Cidade de Deus", "ano": 2002, "descricao": "A história de dois jovens que crescem em uma favela do Rio de Janeiro e tomam caminhos opostos."},
        {"titulo": "Os Infiltrados", "ano": 2006, "descricao": "Um policial e um gângster se infiltram mutuamente em suas organizações rivais em Boston."},
        {"titulo": "Heat", "ano": 1995, "descricao": "Um detetive obsessivo persegue um ladrão profissional em um confronto épico em Los Angeles."},
        {"titulo": "Scarface", "ano": 1983, "descricao": "Um refugiado cubano sobe ao topo do submundo do crime em Miami."},
    ],
    "documentario": [
        {"titulo": "Free Solo", "ano": 2018, "descricao": "O alpinista Alex Honnold tenta escalar o El Capitan sem cordas de segurança."},
        {"titulo": "Amy", "ano": 2015, "descricao": "O retrato íntimo da vida e da música da cantora Amy Winehouse."},
        {"titulo": "Searching for Sugar Man", "ano": 2012, "descricao": "A busca pela verdadeira história do misterioso músico Rodriguez."},
        {"titulo": "13th", "ano": 2016, "descricao": "Uma análise do sistema prisional americano e sua relação com a escravidão e o racismo."},
        {"titulo": "Jiro Dreams of Sushi", "ano": 2011, "descricao": "A dedicação de um mestre sushiman de 85 anos em busca da perfeição."},
    ],
    "familia": [
        {"titulo": "Esqueceram de Mim", "ano": 1990, "descricao": "Um garoto de 8 anos é esquecido em casa enquanto a família viaja e precisa defender a casa de ladrões."},
        {"titulo": "Matilda", "ano": 1996, "descricao": "Uma menina superdotada com poderes telecinéticos enfrenta pais negligentes e uma diretora tirânica."},
        {"titulo": "A Fantástica Fábrica de Chocolate", "ano": 2005, "descricao": "Um garoto pobre ganha um ingresso para visitar a fábrica de chocolate mais mágica do mundo."},
        {"titulo": "Jumanji", "ano": 1995, "descricao": "Duas crianças encontram um jogo de tabuleiro mágico que liberta animais selvagens no mundo real."},
        {"titulo": "O Mágico de Oz", "ano": 1939, "descricao": "Uma garota do Kansas é transportada para um mundo mágico e tenta encontrar o caminho de volta para casa."},
    ],
    "fantasia": [
        {"titulo": "O Senhor dos Anéis: A Sociedade do Anel", "ano": 2001, "descricao": "Um hobbit parte em uma jornada para destruir o Um Anel e salvar a Terra Média."},
        {"titulo": "Harry Potter e a Pedra Filosofal", "ano": 2001, "descricao": "Um menino descobre que é um bruxo e começa sua jornada em uma escola de magia."},
        {"titulo": "O Labirinto do Fauno", "ano": 2006, "descricao": "Uma menina na Espanha pós-guerra descobre um mundo de fantasia mágico e sombrio."},
        {"titulo": "A Princesa Prometida", "ano": 1987, "descricao": "Uma jovem é sequestrada por piratas enquanto o amor de sua vida tenta resgatá-la."},
        {"titulo": "Stardust: O Mistério da Estrela", "ano": 2007, "descricao": "Um jovem atravessa um portal para um reino mágico em busca de uma estrela cadente."},
    ],
    "faroeste": [
        {"titulo": "Três Homens em Conflito", "ano": 1966, "descricao": "Três pistoleiros buscam um tesouro enterrado durante a Guerra Civil Americana."},
        {"titulo": "Django Livre", "ano": 2012, "descricao": "Um ex-escravo embarca numa jornada sangrenta para resgatar sua esposa de um cruel fazendeiro."},
        {"titulo": "Tombstone", "ano": 1993, "descricao": "Wyatt Earp e Doc Holliday enfrentam uma gangue criminosa numa cidade do Velho Oeste."},
        {"titulo": "Irmãos de Sangue", "ano": 2016, "descricao": "Dois irmãos roubam um banco para salvar a fazenda da família e são perseguidos por Texas Rangers."},
        {"titulo": "O Homem das Sombras", "ano": 2007, "descricao": "Um pistoleiro misterioso chega a uma cidade dominada por corrupção e decide agir."},
    ],
    "guerra": [
        {"titulo": "Dunkirk", "ano": 2017, "descricao": "A evacuação de 400 mil soldados aliados cercados pelo exército alemão na Segunda Guerra Mundial."},
        {"titulo": "O Resgate do Soldado Ryan", "ano": 1998, "descricao": "Um grupo de soldados americanos arrisca a vida para encontrar e resgatar um único soldado."},
        {"titulo": "Apocalypse Now", "ano": 1979, "descricao": "Um capitão do exército americano é enviado ao Vietnã para eliminar um coronel renegado."},
        {"titulo": "1917", "ano": 2019, "descricao": "Dois soldados britânicos atravessam território inimigo para entregar uma mensagem que pode salvar 1.600 vidas."},
        {"titulo": "Até o Último Homem", "ano": 2016, "descricao": "Um soldado pacifista se recusa a usar armas, mas se torna um herói na Batalha de Okinawa."},
    ],
    "historia": [
        {"titulo": "Gladiador", "ano": 2000, "descricao": "Um general romano é traído e escravizado, tornando-se um gladiador em busca de vingança."},
        {"titulo": "Braveheart", "ano": 1995, "descricao": "William Wallace lidera a resistência escocesa contra a dominação inglesa no século XIII."},
        {"titulo": "Lincoln", "ano": 2012, "descricao": "Os esforços do presidente Abraham Lincoln para abolir a escravidão nos EUA durante a guerra civil."},
        {"titulo": "O Discurso do Rei", "ano": 2010, "descricao": "O rei George VI supera sua gagueira com a ajuda de um terapeuta para liderar a Grã-Bretanha na guerra."},
        {"titulo": "12 Anos de Escravidão", "ano": 2013, "descricao": "A história real de Solomon Northup, um homem livre sequestrado e vendido como escravo."},
    ],
    "misterio": [
        {"titulo": "Assassinato Sob Encomenda", "ano": 2019, "descricao": "Um detetive famoso investiga um caso de assassinato em uma reunião de família milionária."},
        {"titulo": "Memento", "ano": 2000, "descricao": "Um homem com amnésia tenta encontrar o assassino de sua esposa usando notas e tatuagens."},
        {"titulo": "Shutter Island", "ano": 2010, "descricao": "Um marshal investiga o desaparecimento de uma paciente em um hospital psiquiátrico isolado."},
        {"titulo": "A Janela Indiscreta", "ano": 1954, "descricao": "Um fotógrafo imobilizado acredita ter testemunhado um assassinato pelo apartamento vizinho."},
        {"titulo": "Assassinato no Expresso do Oriente", "ano": 2017, "descricao": "Hercule Poirot investiga um assassinato a bordo de um luxuoso trem preso na neve."},
    ],
    "musica": [
        {"titulo": "Bohemian Rhapsody", "ano": 2018, "descricao": "A trajetória do Queen e de Freddie Mercury até o lendário show no Live Aid."},
        {"titulo": "Rocketman", "ano": 2019, "descricao": "A jornada do músico Elton John desde a infância até o estrelato mundial."},
        {"titulo": "A Star Is Born", "ano": 2018, "descricao": "Uma cantora em ascensão tem sua carreira impulsionada por uma estrela do rock em declínio."},
        {"titulo": "Yesterday", "ano": 2019, "descricao": "Um músico acorda em um mundo onde os Beatles nunca existiram e começa a tocar as músicas deles."},
        {"titulo": "Whiplash", "ano": 2014, "descricao": "Um jovem baterista é submetido a um treinamento extremo por um professor obsessivo em busca da perfeição."},
    ],
}

MAPA_GENEROS = {
    "acao": ["ação", "acao", "luta", "heroi", "herói", "explosao", "explosão", "adrenalina", "combate", "batalha"],
    "aventura": ["aventura", "exploração", "exploracao", "expedição", "expedicao", "jornada", "descoberta", "tesouro"],
    "animacao": ["animação", "animacao", "desenho", "infantil", "pixar", "disney", "anime"],
    "cinema_tv": ["cinema tv", "telefilme", "minissérie", "minisserie", "tv movie"],
    "comedia": ["comedia", "comédia", "engraçado", "engracado", "rir", "humor", "divertido", "risada", "piada"],
    "crime": ["crime", "policial", "gangster", "máfia", "mafia", "roubo", "tráfico", "trafico", "assalto", "bandido"],
    "documentario": ["documentario", "documentário", "documenta", "real", "verdadeiro", "historia real", "história real"],
    "drama": ["drama", "emocionante", "emoção", "emocao", "reflexao", "reflexão", "profundo", "intenso", "serio", "sério"],
    "familia": ["familia", "família", "criança", "criancas", "crianças", "kids", "toda idade", "para criança"],
    "fantasia": ["fantasia", "magico", "mágico", "magia", "feitiço", "feitico", "elfo", "dragao", "dragão", "bruxo", "medieval"],
    "faroeste": ["faroeste", "western", "cowboy", "velho oeste", "xerife", "pistoleiro", "saloon"],
    "ficcao_cientifica": ["ficção", "ficcao", "científica", "cientifica", "sci-fi", "scifi", "nave", "aliens", "alienigena", "futuro", "tecnologia", "robo", "robô", "espaco", "espaço"],
    "guerra": ["guerra", "batalha", "soldado", "militar", "exército", "exercito", "nazista", "segunda guerra", "vietnam"],
    "historia": ["historia", "história", "histórico", "historico", "época", "epoca", "antiguidade", "romano", "medieval", "imperío", "imperio"],
    "misterio": ["misterio", "mistério", "investigação", "investigacao", "detetive", "enigma", "pista", "quem matou", "whodunit"],
    "musica": ["musica", "música", "musical", "cantor", "banda", "show", "concerto", "rock", "jazz", "pop"],
    "romance": ["romance", "amor", "romantico", "romântico", "casal", "paixao", "paixão", "apaixonado", "sentimento"],
    "suspense": ["suspense", "thriller", "tensão", "tensao", "serial killer", "perseguicao", "perseguição"],
    "terror": ["terror", "medo", "assustador", "horror", "susto", "assombrado", "sobrenatural", "sinistro"],
}